name: "Zig"
on:
  push:
    paths:
      - '**.zig'
      - .github/workflows/zig.yml
    branches:
      - main
jobs:
  checks:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig fmt --check .
      - run: zig build test
